# Generated by Django 4.0.4 on 2022-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='date_travel',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='place',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
