# Generated by Django 4.0.4 on 2022-11-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel_date_travel_blogmodel_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='verify',
            field=models.BooleanField(default=True),
        ),
    ]
