# Generated by Django 4.0.4 on 2022-11-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogmodel_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
