# Generated by Django 4.0.4 on 2022-11-11 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('short_discription', models.CharField(help_text='short description place in 50 words', max_length=50)),
                ('discription', models.TextField()),
                ('rel_link', models.URLField(default='https://www.google.com/search?q=kerala&rlz=1C5CHFA_enIN988IN988&oq=ker&aqs=chrome.0.35i39j46i433i512j69i57j69i60l5.1347j0j7&sourceid=chrome&ie=UTF-8', help_text='you can add related articles link about place here')),
                ('link', models.URLField()),
                ('warning', models.TextField(help_text='give any spetial advise or any spectial local warning here')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('verify', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.districts')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.remark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reviewmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('visited', 'visited'), ('Not visited', 'Not visited')], max_length=12)),
                ('rating', models.CharField(blank=True, choices=[('Below average', 'Below average'), ('Average', 'Average'), ('Recomandable', 'Recomandable'), ('Good', 'Good'), ('fentastic', 'fentastic')], max_length=14, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewmodel', to='home.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewmodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='', verbose_name='profile/')),
                ('Bio_head', models.CharField(help_text='like PROFFESSIONAL PHOTOGRAPHER FOR 4 YEARS', max_length=40)),
                ('Name', models.CharField(max_length=20)),
                ('Bio', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilemodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
