# Generated by Django 4.0.4 on 2022-11-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_spot_key_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'ordering': ['district']},
        ),
        migrations.AddField(
            model_name='spot',
            name='ref_img',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='key_words',
            field=models.TextField(help_text='keyword must start with %,keywords give your contribution more expo!'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='rel_link',
            field=models.URLField(default='#', help_text='you can add related articles link about place here'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='warning',
            field=models.TextField(help_text='give any special advise or any special local warning here'),
        ),
    ]
