# Generated by Django 4.0.4 on 2022-11-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_spot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='user',
        ),
    ]
