# Generated by Django 4.0.4 on 2022-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_spot_ref_img2_spot_ref_img3_alter_spot_ref_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='ref_img',
            field=models.CharField(blank=True, help_text='urls/name/', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='ref_img2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='ref_img3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
