# Generated by Django 4.0.4 on 2022-11-02 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_spot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot', to=settings.AUTH_USER_MODEL),
        ),
    ]
