# Generated by Django 4.0.4 on 2022-11-24 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_spot_ref_img_alter_spot_ref_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='spot',
            name='rel_link',
            field=models.URLField(blank=True, help_text='you can add related articles link about place here', null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cluster'),
        ),
    ]
