# Generated by Django 4.0.4 on 2022-11-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_spot_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='danger',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='address',
            new_name='warning',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='longitude',
        ),
        migrations.AddField(
            model_name='spot',
            name='link',
            field=models.EmailField(default=7, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
