# Generated by Django 4.0.4 on 2022-11-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cluster_alter_spot_rel_link_spot_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
