# Generated by Django 4.0.4 on 2022-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_spot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
