# Generated by Django 4.0.4 on 2022-11-05 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_reviewmodel_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spot',
            name='link',
            field=models.URLField(),
        ),
    ]
