# Generated by Django 4.0.4 on 2022-11-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cluster_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(blank=True, choices=[('Below average', '<i class="bi bi-star-fill"></i>'), ('Average', 'Average'), ('Recomandable', 'Recomandable'), ('Good', 'Good'), ('fentastic', 'fentastic')], max_length=14, null=True),
        ),
    ]
