# Generated by Django 4.0.4 on 2022-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(choices=[('Below average', '*'), ('Average', '* *'), ('Recomandable', '* * *'), ('Good', '* * * *'), ('fentastic', '* * * * *')], default='fentastic', max_length=14),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='status',
            field=models.CharField(choices=[('visited', 'visited'), ('Not visited', 'Not visited')], default='visited', max_length=12),
        ),
        migrations.AlterField(
            model_name='spot',
            name='key_words',
            field=models.TextField(help_text='Keywords are used to make your contribution more exposure in the search'),
        ),
        migrations.AlterField(
            model_name='spot',
            name='ref_img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='short_discription',
            field=models.CharField(blank=True, help_text='short title of your description', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='warning',
            field=models.TextField(blank=True, help_text='If you have any special advice for travellers give it here.', null=True),
        ),
    ]
