# Generated by Django 4.0.4 on 2022-11-06 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_reviewmodel_rating_alter_spot_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='', verbose_name='profile/')),
                ('Name', models.CharField(max_length=20)),
                ('Bio', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilemodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
