# Generated by Django 4.0.4 on 2022-11-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_profilemodel_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='account',
            new_name='user',
        ),
    ]
