# Generated by Django 4.0.4 on 2022-11-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_account_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')]),
        ),
    ]
