# Generated by Django 4.0.4 on 2022-11-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='spot',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], null=True),
        ),
    ]
