# Generated by Django 4.0.4 on 2022-11-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_spot_image2_spot_image3_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
