# Generated by Django 4.0.4 on 2022-11-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_districts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
