# Generated by Django 4.0.4 on 2022-11-10 09:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remark_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='discription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
